enum CardElement { fire, water, air, earth }

const String cardsJsonData = '''
[
  { "id": "c1", "name": "Flutter Dash", "element": "air", "power": 120, "description": "Mascota veloz. Compila a la velocidad del sonido.", "icon_ref": "dash" },
  { "id": "c2", "name": "Bug Crítico", "element": "fire", "power": 95, "description": "Calienta la CPU y provoca pánico en producción.", "icon_ref": "bug" },
  { "id": "c3", "name": "Stream de Datos", "element": "water", "power": 105, "description": "Flujo constante. Cuidado con desbordar la memoria.", "icon_ref": "stream" },
  { "id": "c4", "name": "Monolito Legacy", "element": "earth", "power": 160, "description": "Código antiguo. Nadie lo entiende, pero es indestructible.", "icon_ref": "rock" },
  { "id": "c5", "name": "Nube AWS", "element": "air", "power": 85, "description": "Conexión etérea. Cobra por cada respiro.", "icon_ref": "cloud" },
  { "id": "c6", "name": "Hot Reload", "element": "fire", "power": 110, "description": "Cambia la realidad en milisegundos sin perder estado.", "icon_ref": "flash" },
  { "id": "c7", "name": "Null Safety", "element": "water", "power": 130, "description": "Escudo protector contra el abismo del valor nulo.", "icon_ref": "shield" },
  { "id": "c8", "name": "Código Espagueti", "element": "earth", "power": 60, "description": "Enreda al oponente en una lógica imposible de seguir.", "icon_ref": "noodle" },
  { "id": "c9", "name": "Python Script", "element": "earth", "power": 90, "description": "Simple pero letal. Se arrastra por el backend.", "icon_ref": "code" },
  { "id": "c10", "name": "Docker Whale", "element": "water", "power": 140, "description": "Transporta contenedores pesados a través del océano digital.", "icon_ref": "stream" },
  { "id": "c11", "name": "Java Magma", "element": "fire", "power": 125, "description": "Consume mucha RAM pero arde intensamente.", "icon_ref": "fire" },
  { "id": "c12", "name": "Wifi 6E", "element": "air", "power": 100, "description": "Invisible y omnipresente. Baja latencia garantizada.", "icon_ref": "wifi" },
  { "id": "c13", "name": "Firewall", "element": "fire", "power": 150, "description": "Muro de fuego que bloquea accesos no autorizados.", "icon_ref": "security" },
  { "id": "c14", "name": "Git Merge", "element": "water", "power": 115, "description": "Fusiona corrientes de código. A veces causa conflictos.", "icon_ref": "branch" },
  { "id": "c15", "name": "Blockchain", "element": "earth", "power": 170, "description": "Cadena de bloques inmutable. Lento pero seguro.", "icon_ref": "link" },
  { "id": "c16", "name": "Dron Delivery", "element": "air", "power": 75, "description": "Ataque aéreo rápido y automatizado.", "icon_ref": "plane" },
  { "id": "c17", "name": "Linux Penguin", "element": "water", "power": 135, "description": "Kernel de código abierto. Frío y eficiente.", "icon_ref": "snow" },
  { "id": "c18", "name": "Overclock", "element": "fire", "power": 180, "description": "Empuja el hardware al límite. Riesgo de explosión.", "icon_ref": "flash" },
  { "id": "c19", "name": "Garbage Collector", "element": "earth", "power": 95, "description": "Limpia la memoria desechada. Recicla energía.", "icon_ref": "delete" },
  { "id": "c20", "name": "404 Not Found", "element": "air", "power": 50, "description": "El ataque desaparece antes de impactar.", "icon_ref": "error" },
  { "id": "c21", "name": "Blue Screen", "element": "water", "power": 190, "description": "El error fatal. Congela al oponente instantáneamente.", "icon_ref": "desktop" },
  { "id": "c22", "name": "Rust Armor", "element": "earth", "power": 145, "description": "Seguridad de memoria oxidada. Impenetrable.", "icon_ref": "shield" },
  { "id": "c23", "name": "React Atom", "element": "air", "power": 110, "description": "Componente reactivo que gira a gran velocidad.", "icon_ref": "science" },
  { "id": "c24", "name": "SQL Injection", "element": "fire", "power": 130, "description": "Rompe las tablas de la base de datos enemiga.", "icon_ref": "database" },
  { "id": "c25", "name": "Trojan Horse", "element": "earth", "power": 120, "description": "Parece un regalo, pero contiene destrucción.", "icon_ref": "bug" },
  { "id": "c26", "name": "Neural Net", "element": "water", "power": 155, "description": "Aprende de tus movimientos. Se adapta y fluye.", "icon_ref": "brain" },
  { "id": "c27", "name": "5G Tower", "element": "air", "power": 125, "description": "Irradia señales de alta frecuencia.", "icon_ref": "wifi" },
  { "id": "c28", "name": "Incógnito", "element": "air", "power": 80, "description": "Nadie sabe que estuvo aquí. No deja rastro.", "icon_ref": "mask" },
  { "id": "c29", "name": "Cookie Tracker", "element": "earth", "power": 65, "description": "Te sigue a todas partes. Sabe lo que quieres.", "icon_ref": "cookie" },
  { "id": "c30", "name": "Dark Mode", "element": "water", "power": 100, "description": "Descansa la vista y ahorra batería. Sigiloso.", "icon_ref": "moon" },
  { "id": "c31", "name": "RGB Keyboard", "element": "fire", "power": 70, "description": "Más luces significan más FPS. Pura estética.", "icon_ref": "keyboard" },
  { "id": "c32", "name": "Root User", "element": "earth", "power": 200, "description": "Permisos totales. Controla el sistema entero.", "icon_ref": "key" },
  { "id": "c33", "name": "Stack Overflow", "element": "water", "power": 140, "description": "Desbordamiento de pila. Inunda de conocimiento.", "icon_ref": "layers" },
  { "id": "c34", "name": "Infinite Loop", "element": "air", "power": 90, "description": "Atrapa al enemigo en una repetición eterna.", "icon_ref": "loop" },
  { "id": "c35", "name": "Sniper Bot", "element": "fire", "power": 160, "description": "Compra la GPU antes que tú. Precisión inhumana.", "icon_ref": "target" },
  { "id": "c36", "name": "Pixel Art", "element": "earth", "power": 85, "description": "Gráficos retro con encanto sólido.", "icon_ref": "grid" },
  { "id": "c37", "name": "Liquid Cooling", "element": "water", "power": 115, "description": "Mantiene el sistema frío bajo presión.", "icon_ref": "water" },
  { "id": "c38", "name": "Satellite", "element": "air", "power": 135, "description": "Vigilancia orbital global.", "icon_ref": "satellite" },
  { "id": "c39", "name": "Virus .EXE", "element": "fire", "power": 105, "description": "Ejecutable malicioso. Corrompe archivos.", "icon_ref": "skull" },
  { "id": "c40", "name": "C++ Pointer", "element": "earth", "power": 150, "description": "Gestión de memoria manual. Peligroso pero potente.", "icon_ref": "mouse" },
  { "id": "c41", "name": "Rubber Duck", "element": "water", "power": 55, "description": "Escucha tus problemas de código. Terapéutico.", "icon_ref": "duck" },
  { "id": "c42", "name": "Phishing Net", "element": "water", "power": 95, "description": "Pesca contraseñas desprevenidas.", "icon_ref": "hook" },
  { "id": "c43", "name": "Solar Panel", "element": "fire", "power": 120, "description": "Genera energía limpia del sol.", "icon_ref": "sun" },
  { "id": "c44", "name": "Wind Turbine", "element": "air", "power": 125, "description": "Aprovecha las corrientes de aire.", "icon_ref": "fan" },
  { "id": "c45", "name": "Mainframe", "element": "earth", "power": 180, "description": "El gran ordenador central. Inamovible.", "icon_ref": "server" },
  { "id": "c46", "name": "Microchip", "element": "earth", "power": 75, "description": "Pequeño cerebro de silicio.", "icon_ref": "chip" },
  { "id": "c47", "name": "Laser Optico", "element": "fire", "power": 145, "description": "Transmisión de datos a la velocidad de la luz.", "icon_ref": "flash" },
  { "id": "c48", "name": "VPN Tunnel", "element": "water", "power": 110, "description": "Navegación sumergida y privada.", "icon_ref": "lock" },
  { "id": "c49", "name": "Bluetooth", "element": "air", "power": 65, "description": "Conexión de corto alcance. A veces falla.", "icon_ref": "bluetooth" },
  { "id": "c50", "name": "Ransomware", "element": "fire", "power": 175, "description": "Secuestra tus datos hasta que pagues.", "icon_ref": "money" },
  { "id": "c51", "name": "Open Source", "element": "water", "power": 130, "description": "El código fluye libre para todos.", "icon_ref": "heart" },
  { "id": "c52", "name": "T-Rex Runner", "element": "earth", "power": 80, "description": "Aparece cuando no hay internet.", "icon_ref": "dino" },
  { "id": "c53", "name": "BIOS Legacy", "element": "earth", "power": 100, "description": "Sistema básico de entrada/salida.", "icon_ref": "terminal" },
  { "id": "c54", "name": "Thunderbolt", "element": "fire", "power": 155, "description": "Transferencia ultra rápida.", "icon_ref": "flash" },
  { "id": "c55", "name": "Zip Bomb", "element": "air", "power": 195, "description": "Archivo pequeño que explota al descomprimirse.", "icon_ref": "box" },
  { "id": "c56", "name": "Captcha", "element": "water", "power": 85, "description": "Prueba de Turing. Confunde a los bots.", "icon_ref": "robot" },
  { "id": "c57", "name": "Quantum Bit", "element": "air", "power": 200, "description": "Está en dos estados a la vez. Impredecible.", "icon_ref": "atom" },
  { "id": "c58", "name": "GPU Mining", "element": "fire", "power": 165, "description": "Calcula hashes a temperaturas extremas.", "icon_ref": "pickaxe" },
  { "id": "c59", "name": "Floppy Disk", "element": "earth", "power": 55, "description": "Solo 1.44MB de pura nostalgia.", "icon_ref": "save" },
  { "id": "c60", "name": "CSS Grid", "element": "water", "power": 105, "description": "Organiza el caos en una estructura fluida.", "icon_ref": "grid" },
  { "id": "c61", "name": "Sudo Command", "element": "fire", "power": 190, "description": "Hazlo porque yo lo digo.", "icon_ref": "terminal" },
  { "id": "c62", "name": "Brute Force", "element": "earth", "power": 135, "description": "Intenta todas las combinaciones. Fuerza pura.", "icon_ref": "hammer" },
  { "id": "c63", "name": "Cloud Raining", "element": "water", "power": 115, "description": "Almacenamiento que gotea datos.", "icon_ref": "cloud_rain" },
  { "id": "c64", "name": "Spam Bot", "element": "air", "power": 60, "description": "Molesto y numeroso. Llena tu bandeja.", "icon_ref": "mail" },
  { "id": "c65", "name": "Incendio CPU", "element": "fire", "power": 140, "description": "Fallo en el ventilador. Olor a quemado.", "icon_ref": "fire" },
  { "id": "c66", "name": "Typescript", "element": "earth", "power": 125, "description": "JavaScript con armadura y reglas estrictas.", "icon_ref": "shield" },
  { "id": "c67", "name": "Agile Sprint", "element": "air", "power": 110, "description": "Corre rápido antes del deadline.", "icon_ref": "run" },
  { "id": "c68", "name": "Deep Web", "element": "water", "power": 170, "description": "Las profundidades ocultas de internet.", "icon_ref": "anchor" },
  { "id": "c69", "name": "Hacker Hoodie", "element": "fire", "power": 95, "description": "Escribe código verde en pantalla negra.", "icon_ref": "mask" },
  { "id": "c70", "name": "Backup Tape", "element": "earth", "power": 70, "description": "Copia de seguridad lenta pero confiable.", "icon_ref": "cassette" },
  { "id": "c71", "name": "Wireless Charge", "element": "air", "power": 100, "description": "Energía a través del aire.", "icon_ref": "battery" },
  { "id": "c72", "name": "Ping Pong", "element": "water", "power": 85, "description": "Latencia de ida y vuelta.", "icon_ref": "ping" },
  { "id": "c73", "name": "Error 500", "element": "fire", "power": 155, "description": "Fallo interno del servidor. Caos total.", "icon_ref": "error" },
  { "id": "c74", "name": "Blockchain Fork", "element": "earth", "power": 130, "description": "División de la cadena en dos caminos.", "icon_ref": "split" },
  { "id": "c75", "name": "Fiber Optic", "element": "air", "power": 160, "description": "Internet a la velocidad de la luz.", "icon_ref": "cable" },
  { "id": "c76", "name": "Sandbox", "element": "earth", "power": 90, "description": "Entorno seguro para jugar con tierra.", "icon_ref": "box" },
  { "id": "c77", "name": "Memory Leak", "element": "water", "power": 120, "description": "Gotea RAM hasta colapsar el sistema.", "icon_ref": "drop" },
  { "id": "c78", "name": "Zero Day", "element": "fire", "power": 195, "description": "Vulnerabilidad sin parche. Ataque crítico.", "icon_ref": "bomb" },
  { "id": "c79", "name": "White Hat", "element": "air", "power": 140, "description": "Hacker ético que protege el sistema.", "icon_ref": "hat" },
  { "id": "c80", "name": "Hello World", "element": "earth", "power": 50, "description": "El comienzo de todo programa.", "icon_ref": "hand" }
]
''';
